name: my-second-workflow
on:
  push:

jobs:
  job1:
    name: My first job
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Step-1 - commands
        run: |
          pwd
          ls -ltr
          hostname
      
      - name: Step-2 - Checkout
        uses: actions/checkout@v6.1.0
    
      - name: Step-3 - create a file
        run: |
          echo 'pwd' >> myartifact.txt
          mkdir artifacts
          echo 'ls -ltr' >> artifacts/list.txt
          echo 'hostname' >> artifacts/hostname.txt

      - name: Step-4 - upload a file
        uses: actions/upload-artifact@v7.0.1
        with:
    # Artifact name. If the `archive` input is `false`, the name of the file uploaded will be the artifact name.
          name: single_file
    # A file, directory or wildcard pattern that describes what to upload.
          path: ./myartifact.txt

      - name: Upload from dir
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dir_artifacts
          path: artifacts/

      - name: Upload from multiple dirs
        uses: actions/upload-artifact@v7.0.1
        with:
          name: multiple_dirs
          path: |
            ./myartifact.txt
            artifacts/

      - name: Upload from multiple dirs w/exclusions
        uses: actions/upload-artifact@v7.0.1
        with:
          name: multiple_dirs_with_exclusions
          path: |
            ./myartifact.txt
            artifacts/
            !**/hostname.txt



  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checking current dir - pre download
        run: |
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v7
        with: 
          name: single_file
      - name: Checking current dir - post download
        run: |
          pwd
          ls -ltr

  job3: # download directory
    name: JOB3
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Checking current dir - pre download
        run: |
          pwd
          ls -ltr
      - name: Download dir
        uses: actions/download-artifact@v7
        with: 
          name: dir_artifacts
      - name: Checking current dir - post download
        run: |
          pwd
          ls -ltr

  job4: # download in custom location
    name: JOB4
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Create custom folder for download
        run: |
         mkdir -p single_file_dir
         mkdir -p download_dir
      - name: Checking current dir - pre download
        run: |
          pwd
          ls -ltr
      - name: Download single file artifact
        uses: actions/download-artifact@v7
        with: 
          name: single_file
          path: single_file_dir
      - name: Download dir
        uses: actions/download-artifact@v7
        with: 
          name: dir_artifacts
          path: download_dir
      - name: Checking current dir - post download
        run: |
          pwd
          echo "CHECKING SINGLE FILE DIR"
          ls -ltr single_file_dir
          echo "CHECKING DIR ARTIFACTS"
          ls -ltr download_dir
      
