name: my-first-workflow
# will run when a push is made to any branch in the workflow's repository
on:
  schedule:
    - cron: '5 * * * *'

jobs:
  job1:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Running a single cmd in job1
        run: echo "Hi this tis my first GH wf"
      - name: Checking OS release for GH hosted runner
        run: cat /etc/os-release
      - name: Calling sleep
        run: sleep 20
        
  job2:
    name: My second job
    runs-on: ubuntu-latest
    steps:
      - name: Checking hostname for Runner
        run: hostname
      - name: Running multiple cmds
        run: |
          echo "Hi from JOB2"
          echo "current time is 'date'"
          sleep 20

  job3:
    name: My third job
    needs: job1
    runs-on: windows-latest
    steps:
      - name: Job w/single dependency
        run: sleep 10
      - name: Checking Runner info
        shell: pwsh
        run: get-computerinfo
      

  job4:
    name: My fourth job
    needs: [job1, job2, job3]
    runs-on: macos-latest
    steps:
      - name: Job w/multi dependencies
        run: sleep 10
      - name: Checking Runner info
        run: sw_vers

        
    
